services:
  db:
    image: postgres:18
    container_name: product_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - shop_network

  migrator:
    build: .
    container_name: product_migrator
    command: alembic upgrade head
    environment:
      DB_HOST: product_db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shop_network

  app:
    build: .
    container_name: product_app
    ports:
      - "8002:8002"
    environment:
      DB_HOST: product_db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      CART_SERVICE_URL: http://cart_app:8003
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SESSION_SECRET_KEY: ${SESSION_SECRET_KEY}
      AUTH_SERVICE_URL: http://auth_app:8001
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    networks:
      - shop_network

volumes:
  postgres_data:


networks:
  shop_network:
    external: true
