"""remove_rating

Revision ID: 3a25846ccdfe
Revises: 4c521a5b29dc
Create Date: 2026-02-03 16:12:08.786365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a25846ccdfe"
down_revision: Union[str, Sequence[str], None] = "4c521a5b29dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "rating")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "rating",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
