"""add_product_fields

Revision ID: 4c521a5b29dc
Revises: c70bbd31c5df
Create Date: 2026-02-01 13:38:58.005852

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4c521a5b29dc"
down_revision: Union[str, Sequence[str], None] = "c70bbd31c5df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "images",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column("stock", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "products",
        sa.Column("rating", sa.Float(), server_default=sa.text("0.0"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "rating")
    op.drop_column("products", "stock")
    op.drop_column("products", "images")
    # ### end Alembic commands ###
