"""Update product schemas and add schemas for pagination

Revision ID: c70bbd31c5df
Revises: bd52a310330a
Create Date: 2026-01-21 20:40:09.151146

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c70bbd31c5df"
down_revision: Union[str, Sequence[str], None] = "bd52a310330a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
